# Generated by Django 4.1 on 2022-08-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='categoria',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contatos.categoria'),
        ),
    ]
